PLATFORM-8042 update Twiggy extension
Wikia/mediawiki-extensions-Twiggy pull request #5
Opened 2023-02-06 08:28 UTC by mmeller-wikia

https://fandom.atlassian.net/browse/PLATFORM-8042

2023-02-06 08:29 UTC, mmeller-wikia commented on src/Hooks.php
> -	}
Moved to ServiceWiring.php

2023-02-06 20:42 UTC, mszabo-wikia requested changes

2023-02-06 20:42 UTC, mszabo-wikia commented on composer.json
> +        "phan": "vendor/bin/phan -d . --long-progress-bar --load-baseline=.phan-config.php",
That's not a baseline, that's the config file.

2023-02-06 20:42 UTC, mszabo-wikia commented on src/TwiggyService.php
> +		);
`array_diff( $allowedPhpFunctions, $blacklistedPhpFunctions )`

2023-02-06 21:06 UTC, vforge submitted a review, later dismissed

2023-02-06 21:06 UTC, vforge commented on src/PhpFunctionExtension.php
> +			$this->functions
Is that defined? Shouldn't it be assigned in the constructor?

2023-02-06 21:06 UTC, vforge commented on src/TwiggyService.php
> +		);
@mszabo-wikia 👍 is it important that we're losing `array_unique` here?

2023-02-07 00:20 UTC, mszabo-wikia commented on src/TwiggyService.php
> +		);
I think we can keep `array_unique`, I don't expect it to make a big difference but I haven't had time to test yet what Twig would do with duplicate function definitions using the same name.

2023-02-10 09:35 UTC, mszabo-wikia approved these changes

2023-02-15 09:32 UTC, merged

2023-02-15 09:32 UTC, maaartyyynaa commented
Please do not delete this branch